const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(__dirname+'/../app.js','utf8');
class El{constructor(){this.disabled=false;this.hidden=false;this.textContent='';this.children=[];this.events={};this.dataset={};}addEventListener(k,f){this.events[k]=f;}setAttribute(k,v){this[k]=v;}replaceChildren(...v){this.children=v;}appendChild(e){this.children.push(e);}showModal(){this.open=true;}close(){this.open=false;}}
function run(overrides={},provider=null,fail=false){const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../config.js','utf8'),ctx);const c={...ctx.window.MYSE_CONFIG,...overrides};const map=new Map();const q=s=>{if(!map.has(s))map.set(s,new El());return map.get(s);};const groups={'[data-threshold]':[new El(),new El()],'[data-x-handle]':[new El(),new El()],'[data-x-follow]':[new El()],'[data-link]':['x','telegram','x','telegram','x','telegram','x'].map(k=>Object.assign(new El(),{dataset:{link:k}}))};const copied=[];
vm.runInNewContext(source,{window:{MYSE_CONFIG:c,ethereum:provider,addEventListener(){},dispatchEvent(){}},document:{querySelector:q,querySelectorAll:s=>groups[s]||[],createElement:()=>new El()},URL,Map,Event:class{},setTimeout:()=>1,clearTimeout(){},navigator:{clipboard:{writeText:async v=>{if(fail)throw Error();copied.push(v);}}}});return {c,q,groups,copied};}
(async()=>{
let h=run();assert.equal(h.q('#contract-address').textContent,'Not yet published');assert.equal(h.q('#pool-address').textContent,'Not yet published');assert(h.q('#copy-address').disabled&&h.q('#copy-pool').disabled);assert.equal(h.q('#network-name').textContent,'Robinhood Chain (chain id 4663)');assert(h.groups['[data-threshold]'].every(e=>e.textContent==='$5M'));assert(h.groups['[data-link]'].every(e=>/^https:\/\//.test(e.href)));
const a='0x'+'1'.repeat(40),b='0x'+'2'.repeat(40),config={verified:true,contract:a,poolAddress:b,links:{x:'https://x.com/MewYorkExchange',telegram:'https://t.me/MewYorkExchange',trade:'https://example.com/trade',explorer:'https://example.com/token'}};
h=run(config);await h.q('#copy-address').events.click();await h.q('#copy-pool').events.click();assert.deepEqual(h.copied,[a,b]);assert.equal(h.q('#trade-record').children[0].href,config.links.trade);
h=run({...config,verified:false});assert(h.q('#copy-address').disabled&&h.q('#copy-pool').disabled);assert.equal(h.q('#trade-record').textContent,'Not yet published');
h=run({...config,poolAddress:a});assert(h.q('#copy-pool').disabled);h=run({...config,contract:'0x'+'0'.repeat(40)});assert(h.q('#copy-address').disabled);
h=run({...config,links:{trade:'javascript:alert(1)',explorer:'https://user:secret@example.com'}});assert.equal(h.q('#trade-record').textContent,'Not yet published');assert.equal(h.q('#explorer-record').textContent,'Not yet published');
h=run({utilityMarketCapUSD:7500000});assert(h.groups['[data-threshold]'].every(e=>e.textContent==='$7.5M'));
h=run(config,null,true);await h.q('#copy-address').events.click();assert.match(h.q('#notice').textContent,/Couldn’t copy/);
const req=[],listeners={};const provider={isMetaMask:true,request:async({method})=>{req.push(method);return method==='eth_requestAccounts'?[a]:'0x1237';},on:(k,v)=>listeners[k]=v,removeListener:k=>delete listeners[k]};h=run({},provider);h.q('#wallet-open').onclick();const options=()=>h.q('#providers').children;assert.equal(options()[0].textContent,'MetaMask');assert.equal(options()[options().length-1].textContent,'Mobile wallets: available soon');await options()[0].onclick();assert.deepEqual(req,['eth_requestAccounts','eth_chainId']);assert(!h.q('#wallet-status').textContent.includes('Unsupported'));listeners.chainChanged('0x1');assert.match(h.q('#wallet-status').textContent,/Unsupported/);h.q('#disconnect').onclick();assert.equal(Object.keys(listeners).length,0);
const reject={request:async()=>{throw Object.assign(Error(),{code:4001});}};h=run({},reject);h.q('#wallet-open').onclick();assert.equal(h.q('#providers').children[0].textContent,'MetaMask: not detected');await h.q('#providers').children.find(e=>e.textContent==='Browser wallet').onclick();assert.match(h.q('#wallet-status').textContent,/declined/);
h=run();h.q('#wallet-open').onclick();assert.equal(h.q('#providers').children[0].textContent,'MetaMask: not detected');assert(h.q('#providers').children[0].disabled);assert(h.q('#providers').children.some(e=>e.href==='https://metamask.io/download/'));assert(h.q('#providers').children.some(e=>/No browser wallet/.test(e.textContent)));
h=run({walletConnectProjectId:'test-project-id'});h.q('#wallet-open').onclick();const mobile=h.q('#providers').children.find(e=>e.textContent==='WalletConnect (mobile)');assert(mobile&&!mobile.disabled&&typeof mobile.onclick==='function');
console.log('PASS: placeholders, separate full-address copies, verification gates, zero/duplicate addresses, unsafe URLs, config threshold propagation, chain conversion, wallet ordering with MetaMask first, disconnect, rejection, missing wallet and the WalletConnect project-id gate.');
})();
